name: Daily link check
on:
  pull_request:
  schedule:
    - cron: '00 19 * * *' # every day at 19:00 UTC

  workflow_dispatch:
    # Manual trigger

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with: 
          fetch-depth: 0

      - name: Run linkcheck
        working-directory: "docs"
        run: make linkcheck-daily